### ISSUE TITLE
Add marker

### ISSUE THREAD

**Issue by AtulaGuleria** [jessamynsmith/ionic-angular-google-maps-example#1]
How can I add marker to this plugin?

**Comment by jessamynsmith** [comment]
You can see the markers being added here:
[https://github.com/jessamynsmith/ionic-angular-google-maps-example/blob/master/www/js/controllers.js#L54](https://github.com/jessamynsmith/ionic-angular-google-maps-example/blob/master/www/js/controllers.js#L54)
